### PR TITLE
Fix calculation of distance from sphere center to clipping plane.

### PR DESCRIPTION
**Pull request by ggambetta**

### CODE REVIEW

**Comment by Gr1dlock** [comment]
Distance is still not correct, you need to devide it by the length of the normal. That's how the fornula lokks like: 
image

**Comment by ggambetta** [comment]
> The distance is still wrong, you need to devide it by the length of the normal.

The normals are normalized, so the denominator is equal to 1. See here for example: https://github.com/ggambetta/computer-graphics-from-scratch/blob/master/demos/raster-09.html#L455

**Comment by Gr1dlock** [comment]
> > The distance is still wrong, you need to devide it by the length of the normal.
> 
> The normals are normalized, so the denominator is equal to 1. See here for example: https://github.com/ggambetta/computer-graphics-from-scratch/blob/master/demos/raster-09.html#L455

In your example normal is (sqrt(2), 0, sqrt(2)), so it's length is 2

**Comment by ggambetta** [comment]
Argh, you're right, of course. Should have been sqrt(2) / 2. Will fix.

**Comment by ggambetta** [comment]
PTAL.

**Comment by Gr1dlock** [comment]
Sorry, didn't saw this, everything is fine now.

**Pull request merged**
